apiVersion: v1
kind: Namespace
metadata:
  name: assignment2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  namespace: assignment2
  labels:
    app: wordpress-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-deploy
  template:
    metadata:
      labels:
        app: wordpress-deploy
    spec:
      containers:
        - image: wordpress:latest
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service:3306
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: assignment2
  labels:
    app: wordpress-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress-deploy
