apiVersion: v1
kind: Namespace
metadata:
  name: assignment2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: assignment2
  labels:
    app: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deploy
  template:
    metadata:
      labels:
        app: mysql-deploy
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_PASSWORD
              value: wordpress
            - name: MYSQL_ROOT_PASSWORD
              value: wordpress
            - name: MYSQL_ROOT_HOST
              value: '%'
          ports:
            - containerPort: 3306
              name: mysql-deploy

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: assignment2
  labels:
    app: mysql-service
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql-deploy
